(function(g){var window=this;var W4=function(a,b,c){var d=b.wa();g.M(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.zc(c?c:"mqdefault.jpg");var f=b instanceof g.YA&&b.lengthSeconds?g.VL(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.RD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.YA?b.ua:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Wj||g.EM("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.Ih(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.TD&&(d.playlist_length=b.getLength());a.update(d)},X4=function(a){g.V.call(this,{D:"div",
Y:["ytp-upnext","ytp-player-content"],M:{"aria-label":"{{aria_label}}"},K:[{D:"div",I:"ytp-cued-thumbnail-overlay-image",M:{style:"{{background}}"}},{D:"span",I:"ytp-upnext-top",K:[{D:"span",I:"ytp-upnext-header",W:"Up Next"},{D:"span",I:"ytp-upnext-title",W:"{{title}}"},{D:"span",I:"ytp-upnext-author",W:"{{author}}"}]},{D:"a",I:"ytp-upnext-autoplay-icon",M:{role:"button",href:"{{url}}","aria-label":"Play next video"},K:[{D:"svg",M:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},K:[{D:"circle",
I:"ytp-svg-autoplay-circle",M:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",I:"ytp-svg-autoplay-ring",M:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",I:"ytp-svg-fill",M:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",I:"ytp-upnext-bottom",K:[{D:"span",I:"ytp-upnext-cancel"},{D:"span",I:"ytp-upnext-paused",W:"Autoplay is paused"}]}]});
this.B=null;var b=this.o["ytp-upnext-cancel"];this.B=new g.V({D:"button",Y:["ytp-upnext-cancel-button","ytp-button"],M:{tabindex:"0","aria-label":"Cancel autoplay"},W:"Cancel"});g.H(this,this.B);this.B.ia("click",this.lK,this);this.B.ba(b);this.u=a;this.J=this.o["ytp-svg-autoplay-ring"];this.F=this.C=this.w=this.A=null;this.G=new g.K(this.Nm,5E3,this);g.H(this,this.G);this.H=0;this.L(this.o["ytp-upnext-autoplay-icon"],"click",this.VL);this.Tz();this.L(a,"autonavvisibility",this.Tz);this.L(a,"mdxnowautoplaying",
this.nL);this.L(a,"mdxautoplaycanceled",this.oL);this.L(a,"mdxautoplayupnext",this.mC);3==this.u.getPresentingPlayerType()&&(a=(a=g.oL(g.gL(this.u)))?a.ME():null)&&this.mC(a);g.M(this.element,"ytp-upnext-mobile",this.u.O().o)},Y4=function(a,b){if(!a.w){g.Lo("a11y-announce","Up Next "+a.A.title);
a.H=(0,g.lq)();a.w=new g.K((0,g.x)(a.Lp,a,b),25);a.Lp(b);var c=b||g.S(a.u.O().experiments,"autoplay_time")||1E4;a.u.ka("onAutonavCoundownStarted",c)}g.Gn(a.element,"ytp-upnext-autoplay-paused")},$4=function(a){Z4(a);
a.H=(0,g.lq)();a.Lp();g.L(a.element,"ytp-upnext-autoplay-paused")},Z4=function(a){a.w&&(a.w.dispose(),a.w=null)},a5=function(a,b){b=void 0===b?!1:b;
if(g.R(a.u.O().experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.A.wa(),a.Nm(),a.C=new Notification("Up Next",{body:c.title,icon:c.zc()}),a.F=a.L(a.C,"click",a.ML),a.G.start())}Z4(a);a.u.nextVideo(!1,b)},b5=function(a,b){g.V.call(this,{D:"div",
Y:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},tsa=function(a){b5.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.u=new g.V({D:"div",I:"ytp-subscribe-card",K:[{D:"img",I:"ytp-author-image",M:{src:b.Od}},{D:"div",I:"ytp-subscribe-card-right",K:[{D:"div",I:"ytp-author-name",W:b.author},{D:"div",I:"html5-subscribe-button-container"}]}]});g.H(this,this.u);this.u.ba(this.element);this.subscribeButton=new g.kQ("Subscribe",null,"Unsubscribe",null,!0,!1,b.pg,b.subscribed,"trailer-endscreen",null,null,a);g.H(this,this.subscribeButton);this.subscribeButton.ba(this.u.o["html5-subscribe-button-container"]);
this.hide()},c5=function(a){var b=a.O(),c=g.Bv||g.rh?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.V.call(this,{D:"a",Y:e,M:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{D:"div",I:"ytp-videowall-still-image",M:{style:"{{background}}"}},{D:"span",I:"ytp-videowall-still-info",K:[{D:"span",I:"ytp-videowall-still-info-bg",K:[{D:"span",I:"ytp-videowall-still-info-content",M:c,K:[{D:"span",I:"ytp-videowall-still-info-title",W:"{{title}}"},{D:"span",I:"ytp-videowall-still-info-author",
W:"{{author_and_views}}"},{D:"span",I:"ytp-videowall-still-info-live",W:"Live"},{D:"span",I:"ytp-videowall-still-info-duration",W:"{{duration}}"}]}]}]},{D:"span",Y:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",I:"ytp-videowall-still-listlabel-length",K:[" (",{D:"span",W:"{{playlist_length}}"},")"]}]},{D:"span",Y:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{D:"span",I:"ytp-videowall-still-listlabel-length",W:" (50+)"}]}]});this.suggestion=null;this.w=d;this.api=a;this.u=new g.P(this);g.H(this,this.u);this.ia("click",this.onClick);this.ia("keypress",this.B);this.u.L(a,"videodatachange",this.A);g.IL(a,this.element,this);this.A()},usa=function(a){var b=a.suggestion.wa().videoId,c=a.suggestion.getPlaylistId();
(g.DT(a.api.app,b,a.suggestion.Nb,c,void 0,void 0)||a.api.fa("web_player_endscreen_double_log_fix_killswitch"))&&g.KL(a.api,a.element)},d5=function(a){b5.call(this,a,"videowall-endscreen");
var b=this;this.aa=a;this.A=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.H=!1;this.G=null;this.w=new g.P(this);g.H(this,this.w);this.F=new g.K(function(){g.L(b.element,"ytp-show-tiles")},0);
g.H(this,this.F);var c=new g.V({D:"button",Y:["ytp-button","ytp-endscreen-previous"],M:{"aria-label":"Previous"},K:[g.cM()]});g.H(this,c);c.ba(this.element);c.ia("click",this.YG,this);this.table=new g.wC({D:"div",I:"ytp-endscreen-content"});g.H(this,this.table);this.table.ba(this.element);c=new g.V({D:"button",Y:["ytp-button","ytp-endscreen-next"],M:{"aria-label":"Next"},K:[g.dM()]});g.H(this,c);c.ba(this.element);c.ia("click",this.XG,this);this.u=new X4(a);g.H(this,this.u);g.FL(this.player,this.u.element,
4);this.hide()},e5=function(a){return g.GL(a.player)&&a.Dv()&&!a.B},vsa=function(a,b){return(0,g.A)(b.suggestions,function(c){c=g.EN(a.aa.O(),c);
g.H(a,c);return c})},f5=function(a){var b=a.Vr();
b!==a.H&&(a.H=b,a.player.R("autonavvisibility"))},g5=function(a){g.EP.call(this,a);
this.endScreen=null;this.listeners=new g.P(this);g.H(this,this.listeners);this.o=a.O();wsa(a)?this.endScreen=new d5(this.player):this.o.Ia?this.endScreen=new tsa(this.player):this.endScreen=new b5(this.player);g.H(this,this.endScreen);g.FL(this.player,this.endScreen.element,4);this.nB();this.listeners.L(a,"videodatachange",this.nB,this);this.listeners.L(a,g.QD("endscreen"),this.VG,this);this.listeners.L(a,"crx_endscreen",this.DK,this)},wsa=function(a){a=a.O();
return a.Ha&&!a.Ia};
g.r(X4,g.V);g.h=X4.prototype;g.h.Nm=function(){this.C&&(this.G.stop(),this.Wa(this.F),this.F=null,this.C.close(),this.C=null)};
g.h.Tz=function(){g.AC(this,g.hL(this.u))};
g.h.ML=function(){window.focus();this.Nm()};
g.h.hide=function(){g.V.prototype.hide.call(this)};
g.h.Lp=function(a){a=a||g.S(this.u.O().experiments,"autoplay_time")||1E4;var b=Math.min((0,g.lq)()-this.H,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.u.getPresentingPlayerType()?a5(this,!0):this.w&&this.w.start()};
g.h.VL=function(a){!g.Yd(this.B.element,g.Dq(a))&&g.KM(a,this.u)&&a5(this)};
g.h.lK=function(){g.jL(this.u,!0)};
g.h.nL=function(a){this.u.getPresentingPlayerType();this.show();Y4(this,a)};
g.h.mC=function(a){this.u.getPresentingPlayerType();this.A&&this.A.wa().videoId==a.wa().videoId||(this.A=a,W4(this,a,"hqdefault.jpg"))};
g.h.oL=function(){this.u.getPresentingPlayerType();Z4(this);this.hide()};
g.h.X=function(){Z4(this);this.Nm();g.V.prototype.X.call(this)};g.r(b5,g.V);g.h=b5.prototype;g.h.create=function(){this.created=!0};
g.h.destroy=function(){this.created=!1};
g.h.Dv=function(){return!1};
g.h.Vr=function(){return!1};
g.h.Px=function(){return!1};g.r(tsa,b5);g.r(c5,g.V);c5.prototype.onClick=function(a){g.KM(a,this.api,this.w,this.suggestion.Nb||void 0)&&usa(this)};
c5.prototype.B=function(a){switch(a.keyCode){case 13:case 32:g.Iq(a)||(usa(this),g.Hq(a))}};
c5.prototype.A=function(){var a=this.api.getVideoData(),b=this.api.O();this.w=a.sc?!1:b.u};g.r(d5,b5);g.h=d5.prototype;g.h.create=function(){b5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=vsa(this,a),this.videoData=a);this.lg();this.w.L(this.player,"appresize",this.lg);this.w.L(this.player,"onVideoAreaChange",this.lg);this.w.L(this.player,"videodatachange",this.ZG);this.w.L(this.player,"autonavchange",this.Wr);this.w.L(this.player,"autonavcancel",this.WG);a=this.videoData.autonavState;a!==this.G&&this.Wr(a);this.w.L(this.element,"transitionend",this.mN)};
g.h.destroy=function(){g.qr(this.w);g.ie(this.stills);this.stills=[];this.suggestions=null;b5.prototype.destroy.call(this);g.Gn(this.element,"ytp-show-tiles");this.F.stop();this.G=this.videoData.autonavState};
g.h.Dv=function(){return 1!==this.videoData.autonavState};
g.h.show=function(){b5.prototype.show.call(this);g.Gn(this.element,"ytp-show-tiles");this.player.O().o?g.wn(this.F):this.F.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.jL(this.player,!1);e5(this)?(f5(this),2===this.videoData.autonavState?g.R(this.player.O().experiments,"fast_autonav_in_background")&&3===this.player.getVisibilityState()?a5(this.u,!0):Y4(this.u):3===this.videoData.autonavState&&$4(this.u)):(g.jL(this.player,!0),f5(this))};
g.h.hide=function(){b5.prototype.hide.call(this);$4(this.u);f5(this)};
g.h.mN=function(a){g.Dq(a)===this.element&&this.lg()};
g.h.lg=function(){if(this.suggestions&&this.suggestions.length){g.L(this.element,"ytp-endscreen-paginate");var a=g.wL(this.aa,!0,this.aa.isFullscreen()),b=g.RC(this.aa);b&&(b=b.dc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,t=e/2,u=b<=f-2&&n>=t*m,z=e<=k-2&&n>=q*m;if((q+1)/t*d/c>c/(q/(t+1)*d)&&z)n-=q*m,e+=2;else if(u)n-=
t*m,b+=2;else if(z)n-=q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.nd(a.width/m||1,1,1.21);n*=g.nd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.table.element;g.Hh(a,m,n);g.oh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.u;f=this.suggestions[0];c.A=f;W4(c,f,"hqdefault.jpg");g.M(this.element,"ytp-endscreen-takeover",e5(this));f5(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,t=0,d&&f>=b-2&&k>=e-2?t=1:0===k%2&&0===f%2&&(2>k&&2>f?0===k&&0===f&&(t=2):t=2),q=g.od(q+this.A,l),0!==t){u=this.stills[c];u||(u=new c5(this.player),this.stills[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var C=Math.floor(m*f/b),D=Math.floor(n*(k+t)/e)-z-4,E=Math.floor(m*(f+t)/b)-C-4;g.wh(u.element,C,z);g.Hh(u.element,E,D);g.oh(u.element,"transitionDelay",(k+f)/20+"s");g.M(u.element,"ytp-videowall-still-mini",1===t);g.M(u.element,"ytp-videowall-still-large",
2<t);t=u;q=this.suggestions[q];t.suggestion!==q&&(t.suggestion=q,u=t.api.O(),z=g.En(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",W4(t,q,z),g.px(u)&&(u=q.Ih(),u=g.$g(u,g.AD({},"emb_rel_end")),t.ha("url",u)),(q=(q=q.Nb)&&q.itct)&&g.JL(t.api,t.element,q));c++}g.M(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.Vd(e.element),g.he(e);this.stills.length=c}};
g.h.ZG=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.A=0,this.suggestions=vsa(this,a),this.videoData=a,this.lg())};
g.h.XG=function(){this.A+=this.stills.length;this.lg()};
g.h.YG=function(){this.A-=this.stills.length;this.lg()};
g.h.Px=function(){return!!this.u.w};
g.h.Wr=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,Z4(this.u),this.Fa()&&this.lg()):(this.C=!0,this.Fa()&&e5(this)&&(2===a?Y4(this.u):3===a&&$4(this.u)))};
g.h.WG=function(a){if(a){for(a=0;a<this.stills.length;a++)g.LL(this.aa,this.stills[a].element,!0);this.Wr(1)}else this.B=null,this.C=!1;this.lg()};
g.h.Vr=function(){return this.Fa()&&e5(this)};g.r(g5,g.EP);g.h=g5.prototype;g.h.Ey=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!wsa(this.player)||b;var c=a.xi||g.yx(a.La),d=g.YS(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.h.Dy=function(){return this.endScreen.Vr()};
g.h.KF=function(){return this.Dy()?this.endScreen.Px():!1};
g.h.X=function(){g.VQ(this.player.app,"endscreen",void 0);g.EP.prototype.X.call(this)};
g.h.load=function(){g.EP.prototype.load.call(this);this.endScreen.show()};
g.h.unload=function(){g.EP.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.h.VG=function(a){this.Ey()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.h.DK=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.h.nB=function(){g.VQ(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.ND(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});g.H(this,a);var b=new g.ND(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.H(this,b);g.BL(this.player,[a,b])};g.TP.endscreen=g5;})(_yt_player);
